### ISSUE TITLE
Unfriendly error message when EdgeX instance not accessible

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/edgex-cli#137]
# 🐞 Bug Report

### Affected Command

mbhandaru-a01:edgex-cli mbhandaru$ ./edgex-cli version
edgex-cli version:  0.0.1
An error occurred
Get http://192.168.5.202:48080/api/version: dial tcp 192.168.5.202:48080: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14dff24]

goroutine 1 [running]:
github.com/edgexfoundry-holding/edgex-cli/pkg.GetVersion(0x1639903, 0x5, 0x0, 0x0, 0x0)
        /Users/mbhandaru/IoT/edgex/dev/edgex-cli/pkg/client.go:192 +0x114
github.com/edgexfoundry-holding/edgex-cli/cmd/version.NewCommand.func1(0xc0001dfb80, 0x1b4d1a8, 0x0, 0x0)
        /Users/mbhandaru/IoT/edgex/dev/edgex-cli/cmd/version/version.go:22 +0xd1
github.com/spf13/cobra.(*Command).execute(0xc0001dfb80, 0x1b4d1a8, 0x0, 0x0, 0xc0001dfb80, 0x1b4d1a8)
        /Users/mbhandaru/IoT/edgex/dev/edgex-cli/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a2280, 0x1b4d1a8, 0xc000166000, 0x1c)
        /Users/mbhandaru/IoT/edgex/dev/edgex-cli/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mbhandaru/IoT/edgex/dev/edgex-cli/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/edgexfoundry-holding/edgex-cli/cmd.Execute()
        /Users/mbhandaru/IoT/edgex/dev/edgex-cli/cmd/root.go:144 +0x108
main.main()
        /Users/mbhandaru/IoT/edgex/dev/edgex-cli/main.go:22 +0x20
 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
Configure a non-existent edgeX instance  by editing the IP address for hostname  in ~/.edgex-cli/config.yaml file).  The CLI on failing to contact the host returns excessive error message.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**

**Anything else relevant?**

**Comment by difince** [comment]
@mkbhanda As I see, you have been opened this issue three days earlier. That leads me to think that your `/$HOME/.edgex-cli/config.yaml` file is outdated, because the configuration structure had been changed. Delete the file and re-run the CLI ->  the file again, but this time with new content. This will make your testing environment up-to date.

I want to make a few points. 

- Having the above, I am not saying the issue is not relevant anymore. It is relevant and need to be fixed.

- through out the entire project we have this call:
 [host := viper.GetString("host")](https://github.com/edgexfoundry-holding/edgex-cli/blob/ca8c85c80c6eda61391473428f7b681dc48e64f4/pkg/client.go#L182 ) even in `version` command. 
Such common "host" parameter  does not exist in the new configuration. Each microservice have dedicated `host` param  -> this means that a lot of commands currently do not work, because of using ` viper.GetString("host")` It just returns empty string. At all, I see inconsistent usage of when the configuration should come from - there are plain hardcoded places, viper (the file), or using [Conf](https://github.com/edgexfoundry-holding/edgex-cli/blob/ca8c85c80c6eda61391473428f7b681dc48e64f4/config/configuration.go#L28) (the default) structure.  

-  `version` command make a call to ` /core-data/api/v1/version` endpoint only. But actually each Edgex microservice has a dedicate `version`  endpoint. With the current deployment, we have all microservice with one and the same version, but even though probably it is most correct to make a few request ?

**Comment by tonyespy** [comment]
@mkbhanda I think you should change the title to:

"edge-cli: runtime panic when EdgeX isn't running"

In this case, the panic seems to be because a call to Core Data's /api/version endpoint fails, so maybe the problem is more specifically when Core Data isn't running and/or reachable?

I just built from master and got the same error:
```

espy@xen:~/dev/go/src/github.com/edgexfoundry-holding/edgex-cli$ ./edgex-cli version
edgex-cli version:  0.0.1
An error occurred
Get http://:48080/api/version: dial tcp :48080: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x81a6f7]

goroutine 1 [running]:
github.com/edgexfoundry-holding/edgex-cli/pkg.GetVersion(0xa59a3b, 0x5, 0x0, 0x0, 0x0)
        /home/espy/dev/go/src/github.com/edgexfoundry-holding/edgex-cli/pkg/client.go:192 +0x117
github.com/edgexfoundry-holding/edgex-cli/cmd/version.NewCommand.func1(0xc000141900, 0xf26590, 0x0, 0x0)
        /home/espy/dev/go/src/github.com/edgexfoundry-holding/edgex-cli/cmd/version/version.go:22 +0xd0
github.com/spf13/cobra.(*Command).execute(0xc000141900, 0xf26590, 0x0, 0x0, 0xc000141900, 0xf26590)
        /home/espy/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013c000, 0xf26590, 0xc0000b8300, 0x16)
        /home/espy/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/espy/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/edgexfoundry-holding/edgex-cli/cmd.Execute()
        /home/espy/dev/go/src/github.com/edgexfoundry-holding/edgex-cli/cmd/root.go:144 +0x106
main.main()
        /home/espy/dev/go/src/github.com/edgexfoundry-holding/edgex-cli/main.go:22 +0x20

```

**Comment by mkbhanda** [comment]
Hello Tony!

That bug hides 2 issues

With the new config related change,  the hostname empty.

With old config … when edgex-go host unreachable .. instead of “panic” just  unable to contact edgex-go type friendly message better.

Thank you for looking into this. 😊
Malini
