### ISSUE TITLE
clean events and readings

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry-holding/edgex-cli#226]
🚀 Feature Request

### Description
Purge events and associated readings.  Potentially parameterize this with addition of from/to timestamps

### Describe the solution you'd like
You have to use the get events (by start/end time) and then loop through to delete those events captured.  This could take a while.  Might need to consider some sort of "working on it" indicator.

see https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.0#/default/get_v1_event__start___end___limit_

### Describe alternatives you've considered
You may also just request the database to drop that document set (event and reading document collections) and recreate with an empty document set.

**Comment by difince** [comment]
Hi @jpwhitemn, I do not think that it is a good idea edgex-cli to directly interact with the database. Currently, the CLI is unaware what database is used behind the scene.  
I like the idea of having spinner indicating the requests are under execution ... I have created another separate issue about that https://github.com/edgexfoundry-holding/edgex-cli/issues/232
 Still to support cleaning up events and readings, I suggest using these endpoints, as I see them more efficient:
- /api/v1/event/scruball endpoint - It removes all events and readings.
(This endpoint is not present in https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml) I guess it should be added ? 
- Remove all pushed events and their associated readings, and should only be used by the scrubber micro service. (See [here](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.0#/default/delete_v1_event_scrub)) (What is this "scrubber" microservice ? )
- Remove all old events and associated readings based on delimiting age (see [here](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.0#/default/delete_v1_event_removeold_age__age_) )

If you insist on deleting events and readings base on start and end time, I would suggest in order to be efficient  such endpoint to be requested in core-data service
