### ISSUE TITLE
Error while building with GO111MODULE=on

### ISSUE THREAD

**Issue by alexcourouble** [edgexfoundry-holding/edgex-cli#26]
`ambiguous import:` error while building/installing with `GO111MODULE=on`:

```
../../go/pkg/mod/github.com/edgexfoundry/go-mod-core-contracts@v0.1.3/models/event.go:19:2: unknown import path "github.com/ugorji/go/codec": ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/Users/acourouble/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (/Users/acourouble/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181204163529-d75b2dcb6bc8)
```
It seems like edgexfoundry/go-mod-core-contracts is dependent on `github.com/ugorji/go v1.1.4`.

And cobra is dependent on `github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8`.

This error breaks building with `GO111MODULE=on`. The current workaround is to build and install with `GO111MODULE=off`.

**Comment by nkstanchev** [comment]
I propose to have an interim workaround for building with go modules via the replace directive as proposed [here](https://github.com/ugorji/go/issues/279) and [here](https://github.com/gin-gonic/gin/issues/1673#issuecomment-482023570)

**Comment by ugorji** [comment]
FYI: I just released a [go-codec](https://github.com/ugorji/go/) **production release** - version 1.1.7 (finally)

First, it resolves the go.mod impasse where we had different import paths (github.com/ugorji/go and github.com/ugorji/go/codec) causing the ambiguous import error.

This is now fixed by leveraging import cycles to ensure that either one works well and resolves to the same bits.

Please let me know if seeing any issues. If all is well over the next few days, I will close this github issue.

- https://github.com/ugorji/go/releases/latest
- https://github.com/ugorji/go/releases/tag/v1.1.7
